export type LoveCharacter = {
  code: string;
  displayCode: string;
  characterLabel: string;
  name: string;
  title: string;
  catchCopy: string;
  emotionalCopy: string;
  shareCopy: string;
  nightCopy: string;
  description: string;
  lovePattern: string;
  linePattern: string;
  anxietyPattern: string;
  strength: string;
  weakPoint: string;
  beforeSendCheck: string;
  okExamples: string[];
  ngExamples: string[];
  roadmap: string[];
  recommendedLessons: number[];
  ctaText: string;
  compatibility: {
    easy: string[];
    growth: string[];
    careful: string[];
    description: string;
  };
  shareTemplate: {
    title: string;
    body: string;
    saveText: string;
    cta: string;
  };
};

type BaseLoveCharacter = Omit<LoveCharacter, "displayCode" | "characterLabel" | "emotionalCopy" | "shareCopy" | "nightCopy" | "compatibility" | "shareTemplate">;
type LoveCharacterExtra = Pick<LoveCharacter, "displayCode" | "characterLabel" | "emotionalCopy" | "shareCopy" | "nightCopy" | "compatibility" | "shareTemplate">;

const baseLoveCharacters: BaseLoveCharacter[] = [
  {
    code: "WINO",
    name: "待ちすぎ",
    title: "静かに待ちすぎる片思いさん",
    catchCopy: "待てる優しさがあるぶん、自分の気持ちを後回しにしすぎないで。",
    description: "相手からの返信を待ちながら、ひとりで不安を抱えやすいタイプ。「もう送らない方がいいかな」と思いながら、本当はこのまま終わるのが怖い。",
    lovePattern: "好きな人の反応を見ながら、慎重に距離を測る恋愛になりやすい。",
    linePattern: "返信を待つ時間が長くなるほど、送る言葉よりも「送っていいのか」を考えすぎて動けなくなりやすい。",
    anxietyPattern: "嫌われたかも、もう終わったかも、とひとりで悪い方向に考えやすい。",
    strength: "相手を急かさない優しさがある。",
    weakPoint: "自分の気持ちを後回しにして、苦しくなるまで我慢しやすい。",
    beforeSendCheck: "これは会話したいLINE？それとも安心したいLINE？",
    okExamples: ["忙しそうだから、落ち着いた時で大丈夫。これだけ送っておくね。", "ふと思い出して送ってみた笑 また落ち着いた時にでも。", "また話せる時に話そう〜 無理しないでね。"],
    ngExamples: ["なんで返してくれないの？", "私なんかした？", "もういい"],
    roadmap: ["Month1 不安を整える", "Month2 軽い会話を作る", "Month3 会う流れを作る"],
    recommendedLessons: [1, 2, 5],
    ctaText: "今夜送る前に、一回だけ整えてみる",
  },
  {
    code: "WINS",
    name: "整え待ち",
    title: "不安を抱えながら整えようとする人",
    catchCopy: "焦らなくて大丈夫。あなたはちゃんと、崩れない恋愛に近づいてる。",
    description: "不安にはなるけど、すぐにぶつけずに一度考えられるタイプ。恋愛になると揺れるけど、少しずつ自分を整える力がある。",
    lovePattern: "好きになると揺れやすいけど、自分を立て直そうとする力もある。",
    linePattern: "送る前に一度考えられるけど、考えすぎると時間だけが過ぎやすい。",
    anxietyPattern: "不安はあるけど、相手を責めたくない気持ちも強い。",
    strength: "一呼吸おける力がある。",
    weakPoint: "整えようとしすぎて、結局自分の本音を出せないことがある。",
    beforeSendCheck: "明日の自分が見ても、送ってよかったと思えそう？",
    okExamples: ["返事は急がなくて大丈夫だけど、ちょっと共有したくなっただけ笑", "落ち着いた時でいいから、また聞かせて〜", "この前話してたやつ見つけたから送っておくね笑"],
    ngExamples: ["迷惑だったら言って", "忙しいならそう言ってほしい", "私ばっかりだよね"],
    roadmap: ["Month1 返信待ちの不安を整える", "Month2 自然な共有LINEを増やす", "Month3 会話から予定へつなげる"],
    recommendedLessons: [2, 5, 7],
    ctaText: "送って後悔しない一文を選ぶ",
  },
  {
    code: "WIPO",
    name: "考えすぎ",
    title: "考えすぎて動けなくなる人",
    catchCopy: "完璧なLINEじゃなくていい。自然に返せる一文からで大丈夫。",
    description: "何を送るか考えすぎて、結局送れなくなるタイプ。相手にどう思われるかを先に考えて、自分の本音を隠しやすい。",
    lovePattern: "失敗したくない気持ちが強く、好きな人ほど慎重になりやすい。",
    linePattern: "下書きを作っては消して、送るタイミングを逃しやすい。",
    anxietyPattern: "変に思われたくない気持ちが強く、動けなくなる。",
    strength: "相手に配慮できる。",
    weakPoint: "失敗を避けすぎて、関係を進めるきっかけまで失いやすい。",
    beforeSendCheck: "完璧に見せようとして、長くなりすぎていない？",
    okExamples: ["久しぶり。ふと思い出して送ってみた笑 最近どうしてる？", "この前話してたやつ見て、ちょっと思い出した笑", "今週か来週あたり、時間合えばご飯行きたいなと思ってた。"],
    ngExamples: ["送らない方がいいよね？", "変だったらごめん", "急にごめん、迷惑だったら無視して"],
    roadmap: ["Month1 送るハードルを下げる", "Month2 短い共有LINEに慣れる", "Month3 軽い誘い方を覚える"],
    recommendedLessons: [2, 7, 8],
    ctaText: "迷った時にそのまま使える言葉を見る",
  },
  {
    code: "WIPS",
    name: "慎重",
    title: "ゆっくり距離を縮める慎重派",
    catchCopy: "あなたの慎重さは弱さじゃなくて、関係を大事にする力。",
    description: "慎重だけど、ただ待つだけではなく、ちゃんと進め方を考えられるタイプ。急がずに距離を縮めたい人。",
    lovePattern: "早く進めるより、ちゃんと安心できる関係を作りたい。",
    linePattern: "すぐ動くよりも、自然な理由や流れがある時に送る方が安心できる。",
    anxietyPattern: "失敗したくない気持ちから、タイミングを慎重に見すぎる。",
    strength: "関係を雑に進めない。",
    weakPoint: "チャンスが来ても「まだ早いかな」と止まりやすい。",
    beforeSendCheck: "相手が返しやすい話題になっている？",
    okExamples: ["この前話してたやつ見つけたから送っておくね笑", "また時間ある時に話そう〜", "無理ない日で大丈夫だから、またご飯行けたら嬉しいな。"],
    ngExamples: ["今どう思ってる？", "はっきりしてほしい", "私のことどうでもいい？"],
    roadmap: ["Month1 不安とタイミングを整理", "Month2 会話の接点を増やす", "Month3 自然に会う流れへ"],
    recommendedLessons: [5, 7, 10],
    ctaText: "焦らず距離を縮める流れを見る",
  },
  {
    code: "WCNO",
    name: "飲み込み",
    title: "確認したいけど我慢する人",
    catchCopy: "確認したくなるのは悪いことじゃない。言葉の形を整えればいいだけ。",
    description: "本当は「どう思ってる？」と聞きたいけど、重いと思われたくなくて我慢するタイプ。気持ちを飲み込みすぎて、夜に苦しくなりやすい。",
    lovePattern: "好きな人の気持ちを知りたいのに、聞けなくて自分の中で抱えやすい。",
    linePattern: "確認LINEを送りたいのに、我慢してさらに不安が大きくなりやすい。",
    anxietyPattern: "返事が遅いと、自分が何かしたのか確認したくなる。",
    strength: "感情のままぶつけない優しさがある。",
    weakPoint: "我慢しすぎて、急に重いLINEになりやすい。",
    beforeSendCheck: "確認ではなく、会話のきっかけに変えられそう？",
    okExamples: ["この前話してたやつ、ちょっと思い出した笑 また時間ある時聞かせて。", "返事は急がなくて大丈夫だけど、これだけ共有したくなっただけ笑", "また話せる時に話そう〜"],
    ngExamples: ["私なんかした？", "嫌なら言って", "なんか怒ってる？"],
    roadmap: ["Month1 確認欲を整える", "Month2 責めない言い換えを覚える", "Month3 安心を相手任せにしすぎない"],
    recommendedLessons: [3, 4, 6],
    ctaText: "確認LINEを返しやすい一文に変える",
  },
  {
    code: "WCNS",
    name: "ひと呼吸",
    title: "不安を言葉にする前に整えられる人",
    catchCopy: "その一呼吸が、恋愛を少しラクにしてくれる。",
    description: "不安になるけど、すぐに相手へぶつける前に一度立ち止まれるタイプ。確認欲とやさしさのバランスを取ろうとしている。",
    lovePattern: "不安もあるけど、ちゃんと穏やかに進めたい気持ちがある。",
    linePattern: "送る前に自分の状態を見られるので、LINEで空回りしにくい。",
    anxietyPattern: "不安はあるが、相手にどう伝わるかも考えられる。",
    strength: "感情と言葉の間に余白を作れる。",
    weakPoint: "整えようとしすぎて、自分の希望を後回しにしがち。",
    beforeSendCheck: "自分の希望も一文だけ入っている？",
    okExamples: ["無理ない日で大丈夫だから、またご飯行けたら嬉しいな。", "落ち着いた時でいいから、また聞かせて〜", "ちょっとだけ思い出して送ってみた。無理に返さなくて大丈夫。"],
    ngExamples: ["全然大丈夫、気にしないで。ほんとは寂しいけど。", "私はいいよ、合わせる", "なんでもいい"],
    roadmap: ["Month1 自分の気持ちを見つける", "Month2 やさしく希望を出す", "Month3 関係を進める一文を使う"],
    recommendedLessons: [5, 10, 13],
    ctaText: "やさしいまま、自分の希望も伝える",
  },
  {
    code: "WCPO",
    name: "読みすぎ",
    title: "返事で気持ちを測りがちな人",
    catchCopy: "返信の速さだけで、あなたの価値も関係の全部も決まらない。",
    description: "返信速度や文の短さで「脈あり・脈なし」を判断しやすいタイプ。相手のLINEひとつで気分が大きく揺れやすい。",
    lovePattern: "相手の小さな反応を見て、気持ちを読み取ろうとしやすい。",
    linePattern: "既読・未読・返信の短さを見て、相手の気持ちを決めつけやすい。",
    anxietyPattern: "前より返信が短いだけで、嫌われたかもと感じやすい。",
    strength: "小さな変化に気づける。",
    weakPoint: "LINEだけで関係を判断しすぎる。",
    beforeSendCheck: "LINE以外の態度も見て判断できている？",
    okExamples: ["最近忙しそうだから、落ち着いたらまた話そう〜", "この前の話、ちょっと思い出して笑った笑", "またタイミングが合えば行こう〜"],
    ngExamples: ["前より冷たくない？", "返信短いね", "もう私に興味ない？"],
    roadmap: ["Month1 LINEだけで決めない練習", "Month2 会話の接点を増やす", "Month3 会った時の反応も見る"],
    recommendedLessons: [1, 5, 11],
    ctaText: "返信だけで崩れない見方を知る",
  },
  {
    code: "WCPS",
    name: "距離感",
    title: "確認欲を整えながら進める人",
    catchCopy: "不安があるままでも、整えながら前に進める。",
    description: "不安も確認したい気持ちもあるけど、関係を壊さない言い方を探せるタイプ。ちゃんと進めたい気持ちが強い。",
    lovePattern: "曖昧な関係に不安を感じながらも、ちゃんと前に進みたい。",
    linePattern: "確認したい時も、言い方を整えれば関係を止めにくい。",
    anxietyPattern: "曖昧な状態が続くと苦しくなりやすい。",
    strength: "不安を行動に変える力がある。",
    weakPoint: "答えを急ぎすぎると相手に圧が伝わりやすい。",
    beforeSendCheck: "答えを迫るLINEになっていない？",
    okExamples: ["今週か来週あたり、時間合えばご飯行きたいなと思ってた。", "また話せる時に話そう〜", "今日会えてよかった。次はこの前話してた〇〇も行ってみたい。"],
    ngExamples: ["いつ会えるの？", "ちゃんと考えてる？", "どうしたいの？"],
    roadmap: ["Month1 確認欲を整理", "Month2 予定につなげる言い方", "Month3 関係を進める会話"],
    recommendedLessons: [6, 9, 10],
    ctaText: "確認じゃなく、次につながる言葉を選ぶ",
  },
  {
    code: "AINO",
    name: "送って不安",
    title: "勢いで送ったあと不安になる人",
    catchCopy: "送れる力はある。あとは、送る前の一呼吸を足すだけ。",
    description: "その時の気持ちで送れるけど、送ったあとに「重かったかな」と見返しやすいタイプ。素直さがあるぶん、あとから不安が追いかけてくる。",
    lovePattern: "好きな気持ちに素直で、思った時に動ける。",
    linePattern: "送る瞬間は自然でも、送った後に何度も見返して不安になりやすい。",
    anxietyPattern: "返信が来るまで、送った内容を反省し続けやすい。",
    strength: "素直に動ける。",
    weakPoint: "送った後に自分を責めやすい。",
    beforeSendCheck: "送った後の自分が苦しくならない一文？",
    okExamples: ["ふと思い出して送ってみた笑 また落ち着いた時にでも。", "この前話してたやつ見つけたから送っておくね笑", "また時間ある時に話そう。"],
    ngExamples: ["今の重かった？", "変なこと送ったかも", "ごめん忘れて"],
    roadmap: ["Month1 送る前の一呼吸", "Month2 送った後に見返しすぎない", "Month3 自然に誘う練習"],
    recommendedLessons: [2, 3, 5],
    ctaText: "送った後に不安にならない整え方を見る",
  },
  {
    code: "AINS",
    name: "一歩出る",
    title: "自分から動けるけど丁寧な人",
    catchCopy: "あなたの素直さは、ちゃんと整えれば魅力になる。",
    description: "自分から動けるけど、相手への負担も考えられるタイプ。自然体で距離を縮めるのが得意になれる人。",
    lovePattern: "自分からきっかけを作りつつ、相手のペースも大事にできる。",
    linePattern: "軽く共有したり、会話のきっかけを置くのが比較的得意。",
    anxietyPattern: "動いた後に少し不安になることはあるが、崩れにくい。",
    strength: "素直さと配慮のバランスがある。",
    weakPoint: "もっと踏み込んでいい場面でも遠慮しやすい。",
    beforeSendCheck: "遠慮しすぎて、何がしたいか曖昧になっていない？",
    okExamples: ["今週か来週あたり、時間合えばご飯行きたいなと思ってた。", "今日会えてよかった。またタイミングが合えば行こう〜", "最近ちょっと話したいことがあるから、軽く会えたら嬉しい。"],
    ngExamples: ["いつでもいいよ、全部合わせる", "無理なら大丈夫、ほんと大丈夫", "なんでもいいよ"],
    roadmap: ["Month1 自然な会話を作る", "Month2 希望を軽く出す", "Month3 次の予定につなげる"],
    recommendedLessons: [7, 9, 10],
    ctaText: "素直さを重く見せない言い方にする",
  },
  {
    code: "AIPO",
    name: "揺れ",
    title: "追いLINE寸前で迷う人",
    catchCopy: "動きたい気持ちは悪くない。焦りではなく、会話になる形に変えよう。",
    description: "関係を進めたい気持ちはあるけど、相手の反応が気になって迷いやすいタイプ。送るか待つかで、心が忙しくなりやすい。",
    lovePattern: "好きな人との関係を止めたくなくて、自分から動きたくなりやすい。",
    linePattern: "追いLINEしたい時、責めるか我慢するかの二択になりやすい。",
    anxietyPattern: "何もしないと終わりそうで怖くなる。",
    strength: "関係を進めたい意志がある。",
    weakPoint: "焦ると相手の余白を見失いやすい。",
    beforeSendCheck: "返事を求めるより、返しやすいきっかけになっている？",
    okExamples: ["忙しかったら全然あとで大丈夫。また話せる時に話そう〜", "返事は急がなくて大丈夫。これだけ共有しておくね。", "この前話してたやつ見つけたから送っておくね笑"],
    ngExamples: ["見てる？", "なんで返してくれないの？", "もういい"],
    roadmap: ["Month1 追いLINE衝動を止める", "Month2 返しやすい一文に変える", "Month3 会う流れへ進める"],
    recommendedLessons: [3, 4, 6],
    ctaText: "追いLINEの代わりになる一文を見る",
  },
  {
    code: "AIPS",
    name: "進め上手",
    title: "動きながら距離感を整える人",
    catchCopy: "あなたは、追いすぎずに進める力を育てていける。",
    description: "自分から動きつつ、相手との距離感も見ようとできるタイプ。恋愛で不安になることはあっても、学びながら進める。",
    lovePattern: "関係を進めたい気持ちと、重く見られたくない気持ちの両方がある。",
    linePattern: "自分から送れるけど、相手の反応を見て調整できる。",
    anxietyPattern: "進めたい気持ちと、重く見られたくない気持ちの間で揺れる。",
    strength: "行動しながら整えられる。",
    weakPoint: "反応が薄いと急に自信をなくしやすい。",
    beforeSendCheck: "自分のペースだけで進めようとしていない？",
    okExamples: ["無理ない日で大丈夫だから、またご飯行けたら嬉しいな。", "またタイミングが合えば行こう〜", "最近ちょっと話したいことがあるから、軽く会えたら嬉しい。"],
    ngExamples: ["早く会いたい", "なんで予定決めてくれないの？", "私だけ会いたいみたい"],
    roadmap: ["Month1 距離感を整える", "Month2 誘い方を軽くする", "Month3 進展の流れを作る"],
    recommendedLessons: [6, 10, 15],
    ctaText: "追いすぎずに進める流れを見る",
  },
  {
    code: "ACNO",
    name: "確認したい",
    title: "好きが出すぎて確認したくなる人",
    catchCopy: "好きが大きいだけ。責める形じゃなく、伝わる形に整えよう。",
    description: "好きになると、相手の気持ちをすぐ知りたくなるタイプ。「どう思ってる？」を聞きたいけど、重いと思われるのが怖い。",
    lovePattern: "好きな気持ちが大きくなるほど、相手の反応を確認したくなる。",
    linePattern: "気持ちが高まると、相手の反応をすぐ確認したくなる。",
    anxietyPattern: "好きの大きさに対して、相手の反応が足りないと不安になる。",
    strength: "好きな気持ちに素直。",
    weakPoint: "確認が増えると、相手に負担が伝わりやすい。",
    beforeSendCheck: "好きの確認ではなく、会話や予定につながる形になっている？",
    okExamples: ["今週か来週あたり、時間合えばご飯行きたいなと思ってた。", "今日会えてよかった。また話せたら嬉しい。", "また時間ある時に話そう〜"],
    ngExamples: ["私のことどう思ってる？", "好きなの？違うの？", "はっきりして"],
    roadmap: ["Month1 確認LINEを整える", "Month2 好意を軽く出す", "Month3 会う時間を増やす"],
    recommendedLessons: [4, 10, 12],
    ctaText: "好きが重く見えない伝え方を見る",
  },
  {
    code: "ACNS",
    name: "素直安定",
    title: "素直だけど重くならない工夫ができる人",
    catchCopy: "素直な気持ちは、言い方を整えるだけでちゃんと届きやすくなる。",
    description: "気持ちは出せるけど、自分の伝え方も見直せるタイプ。素直さと落ち着きのバランスが取れるようになる人。",
    lovePattern: "素直に伝えたい気持ちと、相手の受け取りやすさの両方を見られる。",
    linePattern: "好意や希望を出しつつ、相手の余白も残せる。",
    anxietyPattern: "不安はあるが、伝え方を考える余裕もある。",
    strength: "素直さと自分軸のバランスが育ちやすい。",
    weakPoint: "相手に合わせすぎると、自分の希望を薄めすぎる。",
    beforeSendCheck: "自分の気持ちを消しすぎていない？",
    okExamples: ["無理ない日で大丈夫だから、またご飯行けたら嬉しいな。", "今日普通に楽しかった。また行きたい笑", "最近ちょっと話したいことがあるから、軽く会えたら嬉しい。"],
    ngExamples: ["なんでもいい", "全部合わせる", "私は大丈夫"],
    roadmap: ["Month1 自分の気持ちを見つける", "Month2 希望を軽く伝える", "Month3 関係を進める"],
    recommendedLessons: [9, 10, 13],
    ctaText: "素直なまま、重くならない言葉を見る",
  },
  {
    code: "ACPO",
    name: "空回り",
    title: "不安で空回りしやすい人",
    catchCopy: "空回りしてしまうのは、ちゃんと大切にしたい気持ちがあるから。",
    description: "関係を進めたい気持ちが強く、不安になると確認や追いLINEに寄りやすいタイプ。好きだからこそ、焦りが前に出やすい。",
    lovePattern: "大切にしたい気持ちが強いほど、早く安心したくなりやすい。",
    linePattern: "不安になると、確認・催促・長文になりやすい。",
    anxietyPattern: "返事が遅いだけで、関係が終わるように感じやすい。",
    strength: "真剣に向き合える。",
    weakPoint: "焦ると、相手に余白を残せなくなる。",
    beforeSendCheck: "相手が返さないと悪い空気になっていない？",
    okExamples: ["忙しそうだから、落ち着いた時で大丈夫。これだけ送っておくね。", "また話せる時に話そう〜 無理しないでね。", "返事は急がなくて大丈夫。これだけ共有しておくね。"],
    ngExamples: ["なんで返してくれないの？", "私なんかした？", "もういい"],
    roadmap: ["Month1 不安のまま送らない", "Month2 追いLINEを言い換える", "Month3 会う流れを整える"],
    recommendedLessons: [1, 3, 4],
    ctaText: "不安で送る前に、一回だけ整える",
  },
  {
    code: "ACPS",
    name: "育て上手",
    title: "ちゃんと進めたい恋愛努力家",
    catchCopy: "あなたは、恋愛を雑にしない人。だからこそ、整え方を知れば強い。",
    description: "不安もあるけど、関係をちゃんと育てたい気持ちが強いタイプ。学びながら、送る言葉や距離感を整えていける。",
    lovePattern: "好きな人との関係を、ちゃんと育てたい気持ちが強い。",
    linePattern: "好きな気持ちと進めたい気持ちを、行動に移せる。",
    anxietyPattern: "ちゃんと進めたいからこそ、曖昧な状態に不安を感じやすい。",
    strength: "学びながら改善できる。",
    weakPoint: "結果を急ぐと、焦りが出やすい。",
    beforeSendCheck: "今日のLINEは関係を進めるため？不安を消すため？",
    okExamples: ["今週か来週あたり、時間合えばご飯行きたいなと思ってた。", "今日会えてよかった。次は〇〇も行ってみたい。", "無理ない日で大丈夫だから、またご飯行けたら嬉しいな。"],
    ngExamples: ["いつになったら進むの？", "どう思ってるの？", "ちゃんと考えてる？"],
    roadmap: ["Month1 不安を整える", "Month2 会う流れを作る", "Month3 関係を進める"],
    recommendedLessons: [10, 14, 15],
    ctaText: "ちゃんと進めたい恋に必要な言葉を見る",
  },
];

const loveCharacterExtras: Record<string, LoveCharacterExtra> = {
  WINO: {
    displayCode: "WAIT",
    characterLabel: "待ちすぎ",
    emotionalCopy: "待てるのはやさしさ。でも、ひとりで抱え込みすぎなくていい。",
    shareCopy: "私はたぶん、待ちすぎ。",
    nightCopy: "返事を待っている間も、あなたの価値は減っていません。",
    compatibility: {
      easy: ["CALM", "EASE", "GLOW"],
      growth: ["MOVE", "FLOW", "GROW"],
      careful: ["LOOP", "SEEK", "READ"],
      description: "待ちすぎは、落ち着いて受け止めてくれる相手だと安心しやすいです。反対に、確認や不安が強く出る相手とは、お互いに考えすぎやすくなることがあります。",
    },
    shareTemplate: {
      title: "WAIT｜待ちすぎ",
      body: "返信を待てるのは、やさしさ。\nでも、待っている間に自分だけが苦しくなっているなら、\n少しだけ整えてあげていい。",
      saveText: "待つ恋でしんどくなりやすい人へ。",
      cta: "あなたはどのタイプだった？",
    },
  },
  WINS: {
    displayCode: "CALM",
    characterLabel: "整え待ち",
    emotionalCopy: "不安になっても、すぐ壊さないように整えようとする人。",
    shareCopy: "私はたぶん、整え待ち。",
    nightCopy: "一呼吸おけるあなたは、ちゃんと恋を大切にできています。",
    compatibility: {
      easy: ["EASE", "GLOW", "TACT"],
      growth: ["MOVE", "FLOW", "GROW"],
      careful: ["LOOP", "PING", "SEEK"],
      description: "整え待ちは、感情を急かされない関係で力を発揮しやすいです。相手の不安が強い時は、全部受け止めようとしすぎないことが大切です。",
    },
    shareTemplate: {
      title: "CALM｜整え待ち",
      body: "不安になっても、すぐにはぶつけない。\nちゃんと一度、自分の中で整えようとする。\nその落ち着きは、恋を壊さない力になる。",
      saveText: "不安を抱えながらも整えようとする人へ。",
      cta: "診断結果、スクショして保存してね。",
    },
  },
  WIPO: {
    displayCode: "SPIN",
    characterLabel: "考えすぎ",
    emotionalCopy: "ちゃんと考える人ほど、送る前に止まってしまう夜がある。",
    shareCopy: "私はたぶん、考えすぎ。",
    nightCopy: "完璧なLINEじゃなくていい。伝わる一文で大丈夫。",
    compatibility: {
      easy: ["WAIT", "CALM", "PACE"],
      growth: ["EASE", "GLOW", "MOVE"],
      careful: ["READ", "LOOP", "SWAY"],
      description: "考えすぎは、ゆっくり待ってくれる相手と安心しやすいです。読みすぎや空回りが重なると、LINEひとつでお互いに不安が大きくなることがあります。",
    },
    shareTemplate: {
      title: "SPIN｜考えすぎ",
      body: "何を送るか考えて、\n消して、また考えて。\n好きだからこそ、LINEひとつが重くなる夜がある。",
      saveText: "送る前に考えすぎる人へ。",
      cta: "これ私かもと思ったら保存。",
    },
  },
  WIPS: {
    displayCode: "PACE",
    characterLabel: "慎重",
    emotionalCopy: "急がないのは、好きじゃないからじゃなくて、大事にしたいから。",
    shareCopy: "私はたぶん、慎重。",
    nightCopy: "ゆっくりでも、ちゃんと近づこうとしているなら大丈夫。",
    compatibility: {
      easy: ["WAIT", "CALM", "EASE"],
      growth: ["FLOW", "GROW", "GLOW"],
      careful: ["SEEK", "LOOP", "PING"],
      description: "慎重は、急がず関係を育てられる相手と相性がよいです。進展を急ぐ相手とは、ペースの違いを言葉にすることが大切です。",
    },
    shareTemplate: {
      title: "PACE｜慎重",
      body: "急がないのは、気持ちがないからじゃない。\nちゃんと大事に進めたいから。\nゆっくりでも、恋は進めていい。",
      saveText: "慎重に恋を進めたい人へ。",
      cta: "あなたの恋愛タイプも見てみて。",
    },
  },
  WCNO: {
    displayCode: "HUSH",
    characterLabel: "飲み込み",
    emotionalCopy: "言えないのは弱さじゃない。重くなりたくないくらい、大切にしてるだけ。",
    shareCopy: "私はたぶん、飲み込み。",
    nightCopy: "飲み込んだ気持ちも、ちゃんとあなたの本音です。",
    compatibility: {
      easy: ["EASE", "CALM", "GLOW"],
      growth: ["TACT", "GROW", "MOVE"],
      careful: ["SEEK", "LOOP", "READ"],
      description: "飲み込みは、本音を急かさず聞いてくれる相手だと安心できます。確認が強い相手には、我慢しすぎてしまわないよう注意が必要です。",
    },
    shareTemplate: {
      title: "HUSH｜飲み込み",
      body: "言いたいことがあるのに、\n重いと思われたくなくて飲み込む。\nその我慢、ちゃんと気づいてあげて。",
      saveText: "本音を飲み込みやすい人へ。",
      cta: "夜に見返せるように保存してね。",
    },
  },
  WCNS: {
    displayCode: "EASE",
    characterLabel: "ひと呼吸",
    emotionalCopy: "不安をぶつける前に、ちゃんと自分を整えようとする人。",
    shareCopy: "私はたぶん、ひと呼吸。",
    nightCopy: "落ち着こうとできるあなたは、もう十分がんばっています。",
    compatibility: {
      easy: ["CALM", "GLOW", "TACT"],
      growth: ["WAIT", "MOVE", "GROW"],
      careful: ["LOOP", "SWAY", "PING"],
      description: "ひと呼吸は、多くのタイプと穏やかに関係を作りやすいです。ただし、不安が強い相手を全部支えようとすると疲れやすいので、自分の気持ちも大切にしてください。",
    },
    shareTemplate: {
      title: "EASE｜ひと呼吸",
      body: "感情のまま送らない。\n一回止まって、言葉を整えられる。\nその一呼吸が、恋を少しラクにしてくれる。",
      saveText: "送る前に立ち止まれる人へ。",
      cta: "あなたはどのタイプだった？",
    },
  },
  WCPO: {
    displayCode: "READ",
    characterLabel: "読みすぎ",
    emotionalCopy: "返信の短さで、気持ちまで決まった気がしてしまう人。",
    shareCopy: "私はたぶん、読みすぎ。",
    nightCopy: "LINEの温度だけで、関係の全部を決めなくて大丈夫。",
    compatibility: {
      easy: ["CALM", "EASE", "TACT"],
      growth: ["GLOW", "GROW", "FLOW"],
      careful: ["LOOP", "SEEK", "SPIN"],
      description: "読みすぎは、言葉の温度が安定している相手だと安心しやすいです。お互いに深読みしやすい相手とは、事実に戻る会話が大切です。",
    },
    shareTemplate: {
      title: "READ｜読みすぎ",
      body: "返信が短いだけで、\n前より冷たい気がしてしまう。\nでも、LINEだけで全部を決めなくていい。",
      saveText: "返信の温度で不安になる人へ。",
      cta: "これ私っぽいと思ったら保存。",
    },
  },
  WCPS: {
    displayCode: "TACT",
    characterLabel: "距離感",
    emotionalCopy: "近づきたい。でも、踏み込みすぎたくない。その間で揺れる人。",
    shareCopy: "私はたぶん、距離感。",
    nightCopy: "ちょうどいい距離を探せるあなたは、恋を雑にしていません。",
    compatibility: {
      easy: ["EASE", "GLOW", "CALM"],
      growth: ["MOVE", "FLOW", "GROW"],
      careful: ["SEEK", "LOOP", "HUSH"],
      description: "距離感は、相手のペースを見られるぶん、関係を整えやすいです。ただし、相手に合わせすぎると自分の本音が見えにくくなるので注意してください。",
    },
    shareTemplate: {
      title: "TACT｜距離感",
      body: "近づきたい。\nでも、踏み込みすぎたくない。\nその距離感を考えられるのは、恋を大事にしている証拠。",
      saveText: "距離感で悩みやすい人へ。",
      cta: "診断して自分のタイプを見る。",
    },
  },
  AINO: {
    displayCode: "PING",
    characterLabel: "送って不安",
    emotionalCopy: "送れる勇気はある。でも、送ったあとに自分を責めてしまう人。",
    shareCopy: "私はたぶん、送って不安。",
    nightCopy: "送れたことは、ちゃんと一歩です。責めなくて大丈夫。",
    compatibility: {
      easy: ["CALM", "EASE", "GLOW"],
      growth: ["MOVE", "FLOW", "GROW"],
      careful: ["LOOP", "SEEK", "READ"],
      description: "送って不安は、送った後に安心できる反応をくれる相手だと落ち着きやすいです。反応が読みにくい相手とは、送った後に自分を責めすぎない工夫が必要です。",
    },
    shareTemplate: {
      title: "PING｜送って不安",
      body: "送るまでは勢いがあるのに、\n送ったあとに急に不安になる。\nでも、送れたことはちゃんと一歩。",
      saveText: "送った後に見返しすぎる人へ。",
      cta: "この結果、スクショして保存してね。",
    },
  },
  AINS: {
    displayCode: "MOVE",
    characterLabel: "一歩出る",
    emotionalCopy: "待つだけじゃなく、自分から恋を動かせる人。",
    shareCopy: "私はたぶん、一歩出る。",
    nightCopy: "自分から動けるあなたは、恋を前に進める力があります。",
    compatibility: {
      easy: ["GLOW", "FLOW", "GROW"],
      growth: ["WAIT", "PACE", "HUSH"],
      careful: ["LOOP", "SWAY", "SEEK"],
      description: "一歩出るは、関係を前に進める力があります。待ち型の相手とは良いきっかけを作れますが、相手のペースを置いていかないことが大切です。",
    },
    shareTemplate: {
      title: "MOVE｜一歩出る",
      body: "待つだけじゃなく、自分から動ける。\nその一歩が、恋を前に進めることもある。\nでも、ひとりで背負いすぎなくていい。",
      saveText: "自分から動けるけど疲れやすい人へ。",
      cta: "あなたの恋愛タイプも見てみて。",
    },
  },
  AIPO: {
    displayCode: "SWAY",
    characterLabel: "揺れ",
    emotionalCopy: "行きたい。引きたい。好きだからこそ、心が何度も揺れる人。",
    shareCopy: "私はたぶん、揺れ。",
    nightCopy: "揺れるのは、本気で大切にしたい気持ちがあるからです。",
    compatibility: {
      easy: ["CALM", "EASE", "TACT"],
      growth: ["GLOW", "FLOW", "GROW"],
      careful: ["SPIN", "LOOP", "READ"],
      description: "揺れは、落ち着いた相手といると気持ちを整えやすいです。不安が重なりやすい相手とは、送る前に一呼吸置くルールがあると安心です。",
    },
    shareTemplate: {
      title: "SWAY｜揺れ",
      body: "送りたい。\nでも怖い。\n行きたい気持ちと引きたい気持ちの間で、\n何度も揺れる夜がある。",
      saveText: "恋愛で気持ちが揺れやすい人へ。",
      cta: "これ私かもと思ったら保存。",
    },
  },
  AIPS: {
    displayCode: "FLOW",
    characterLabel: "進め上手",
    emotionalCopy: "自然に動ける。でも、本当はちゃんと空気を見ている人。",
    shareCopy: "私はたぶん、進め上手。",
    nightCopy: "うまく進めようとしすぎず、あなたの自然さも大切にしていい。",
    compatibility: {
      easy: ["MOVE", "GLOW", "GROW"],
      growth: ["WAIT", "PACE", "HUSH"],
      careful: ["SEEK", "LOOP", "PING"],
      description: "進め上手は、自然に流れを作れるタイプです。相手が不安になりやすい場合は、軽い安心感を添えると関係が進みやすくなります。",
    },
    shareTemplate: {
      title: "FLOW｜進め上手",
      body: "自然に会話を広げられる。\nでも実は、ちゃんと空気も見ている。\nその自然さは、恋を進める力になる。",
      saveText: "自然に距離を縮めたい人へ。",
      cta: "診断結果をストーリーに載せてもOK。",
    },
  },
  ACNO: {
    displayCode: "SEEK",
    characterLabel: "確認したい",
    emotionalCopy: "好きだから、曖昧なままでは不安になる人。",
    shareCopy: "私はたぶん、確認したい。",
    nightCopy: "確かめたい気持ちは悪くありません。伝え方を整えれば大丈夫。",
    compatibility: {
      easy: ["EASE", "TACT", "GLOW"],
      growth: ["CALM", "GROW", "FLOW"],
      careful: ["LOOP", "HUSH", "READ"],
      description: "確認したいは、曖昧さをやさしくほどいてくれる相手だと安心できます。確認が強くなりすぎると、相手が引いてしまうことがあるので、言い方を整えることが大切です。",
    },
    shareTemplate: {
      title: "SEEK｜確認したい",
      body: "好きだから、確かめたくなる。\n曖昧なままだと、不安になる。\n確認したい気持ちは、悪いものじゃない。",
      saveText: "相手の気持ちを確認したくなる人へ。",
      cta: "送る前に見返せるように保存。",
    },
  },
  ACNS: {
    displayCode: "GLOW",
    characterLabel: "素直安定",
    emotionalCopy: "素直に好きでいられて、でもちゃんと落ち着ける人。",
    shareCopy: "私はたぶん、素直安定。",
    nightCopy: "その素直さは、恋の中でもちゃんと魅力になります。",
    compatibility: {
      easy: ["CALM", "EASE", "FLOW"],
      growth: ["WAIT", "MOVE", "GROW"],
      careful: ["LOOP", "READ", "SEEK"],
      description: "素直安定は、恋愛の温度感が安定しているタイプです。多くのタイプと合わせやすいですが、相手に合わせすぎて自分の違和感を見逃さないようにしてください。",
    },
    shareTemplate: {
      title: "GLOW｜素直安定",
      body: "素直に好きでいられて、\nでも感情だけでぶつけすぎない。\nその安定感は、ちゃんと魅力。",
      saveText: "素直さと落ち着きを大事にしたい人へ。",
      cta: "あなたの恋愛タイプも診断してみて。",
    },
  },
  ACPO: {
    displayCode: "LOOP",
    characterLabel: "空回り",
    emotionalCopy: "大切にしたいほど、不安が先に走ってしまう人。",
    shareCopy: "私はたぶん、空回り。",
    nightCopy: "空回りするのは、ダメだからじゃない。大切にしたい気持ちが大きいだけ。",
    compatibility: {
      easy: ["CALM", "EASE", "GLOW"],
      growth: ["TACT", "FLOW", "GROW"],
      careful: ["SEEK", "READ", "SWAY"],
      description: "空回りは、安心感をくれる相手といると落ち着きやすいです。不安が強く出る相手同士だと、お互いに確認や深読みが増えやすいので、送る前の一呼吸が大切です。",
    },
    shareTemplate: {
      title: "LOOP｜空回り",
      body: "大切にしたいほど、不安が先に走る。\n確認したくなるのも、追いかけたくなるのも、\nちゃんと好きだから。",
      saveText: "不安で空回りしやすい人へ。",
      cta: "これ私すぎると思ったら保存。",
    },
  },
  ACPS: {
    displayCode: "GROW",
    characterLabel: "育て上手",
    emotionalCopy: "その場の気持ちだけじゃなく、関係をちゃんと育てたい人。",
    shareCopy: "私はたぶん、育て上手。",
    nightCopy: "ちゃんと進めたいあなたは、恋を雑に扱わない人です。",
    compatibility: {
      easy: ["GLOW", "FLOW", "EASE"],
      growth: ["WAIT", "MOVE", "SEEK"],
      careful: ["LOOP", "HUSH", "PING"],
      description: "育て上手は、関係を長く育てる視点があります。不安が強い相手にも寄り添えますが、全部背負いすぎないことが大切です。",
    },
    shareTemplate: {
      title: "GROW｜育て上手",
      body: "恋をその場の感情だけで終わらせない。\nちゃんと関係として育てたい。\nそのまじめさは、あなたの強さ。",
      saveText: "ちゃんと関係を育てたい人へ。",
      cta: "診断結果をスクショして保存してね。",
    },
  },
};

export const loveCharacters: LoveCharacter[] = baseLoveCharacters.map((character) => ({
  ...character,
  ...loveCharacterExtras[character.code],
}));

export const getLoveCharacter = (code?: string) => {
  const normalized = code?.toUpperCase();
  return loveCharacters.find((character) => character.code === normalized || character.displayCode === normalized);
};

export const getCharacterHref = (character: LoveCharacter) => `/types/${character.displayCode.toLowerCase()}`;
